### ISSUE TITLE
Add a custom Conduit Item

### ISSUE THREAD

**Issue by Koynax** [AlmostReliable/kubejs-enderio#5]
### Describe the feature/addition!

Customize the Item Conduit :
-Item transfer spee.
-Number of items transferred.
-Possibility of upgrading or not (filter, speed, etc.).

### Why would like to see this feature/addition?

To be able to make several tiers of Item Conduit for my modpack .

**Comment by rlnt** [comment]
I thought about this when developing the custom energy conduits but got rid of the idea because the base item conduits support upgrades to increase speed and stack size. I am not sure whether I should add an option to have a custom one. This would also bloat the mod a lot since it would require a custom menu and screen. 90% of the code would be for this custom conduit then.

**Comment by Koynax** [comment]
It was mainly to be able to create a “Tiers” system, which is more practical. 
I had the idea of making :
-Tier 1: 1/t
-Tier 2: 2/t
-Tier 3: 4/t
-Tier 4: 8/t
-Tier 5: 16/t

With upgrades it's not possible to do that, unfortunately.

**Comment by rlnt** [comment]
So the goal is to have tiered item conduits but no upgrade functionality at all, right? I think this could be done. But I can't give any promise or an ETA. Don't have a lot of time with all the 1.21+ changes I have to deal with on other mods. 🫠

**Comment by Koynax** [comment]
Yes, that's it.

Okay, no worries. Courage for your projects. Thanks for your answers ;)

**Comment by rlnt** [comment]
I decided to not add this feature. It's just too much bloat.
Since EnderIO switched to data-driven Conduits on 1.21+ and I already added support for this in the new version, I think I won't deal with 1.20 anymore. Sorry for the inconvenience.
